name: thelper
channels:
  - pytorch
  - conda-forge
dependencies:
  - albumentations
  - cython
  - ddt
  - flake8
  - gitdb
  - gitpython
  - lz4
  - matplotlib
  - mock
  - numpy
  - opencv
  - pillow
  - pip
  - pyopenssl
  - pytest
  - pytest-cov
  - pytest-mock
  - pytorch
  - pyyaml
  - scipy
  - scikit-learn
  - six
  - torchvision
  - tox
  - tqdm
  - pip:
    - augmentor
    - h5py
    - imgaug==0.2.5
    - opencv-python
    - pynput
    - tensorboardX
