name: thelper
channels:
  - pytorch
  - albumentations
dependencies:
  - pytorch=0.4.0
  - numpy
  - cython
  - matplotlib
  - opencv
  - scikit-learn
  - gitpython
  - mock
  - tqdm
  - shapely
  - albumentations
  - pip:
    - imgaug
    - augmentor
    - tensorboardX
    - torchvision
    - pynput
