name: thelper
channels:
  - pytorch
  - conda-forge
dependencies:
  - albumentations
  - affine
  - cython
  - ddt
  - gdal
  - gitdb
  - gitpython
  - lz4
  - matplotlib
  - mock
  - numpy
  - opencv
  - pip
  - pyproj
  - pytest
  - pytest-cov
  - pytest-mock
  - pytorch
  - pyyaml
  - scikit-learn
  - shapely
  - torchvision
  - tqdm
  - pip:
    - augmentor
    - h5py
    - imgaug==0.2.5
    - opencv-python
    - pynput
    - tensorboardX
