name: thelper
channels:
  - pytorch
dependencies:
  - pytorch=0.4.0
  - numpy
  - tensorflow
  - cython
  - matplotlib
  - opencv
  - scikit-learn
  - gitpython
  - mock
  - tqdm
  - pip:
    - augmentor
    - tensorboardX==1.2
    - torchvision
    - pynput
